DepartsCRUD/WebApp/Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using static System.Net.Mime.MediaTypeNames;

namespace WebApp.Controllers
{
    public class DepartmentsController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [Route("/department-list/{filter?}")]
        public IActionResult SearchDepartments(string? filter)
        {
            //var departments = DepartmentsRepository.GetDepartments(filter);
            //return PartialView("_DepartmentList", departments);

            return ViewComponent("DepartmentList", new { filter = filter });
        }


        [HttpGet]
        public IActionResult Details(int id)
        {
            var department = DepartmentsRepository.GetDepartmentById(id);
            if (department == null)
            {
                return View("Error", new List<string>() { "Department not found." });
            }

            return View(department);
            
        }

        [HttpPost]
        public IActionResult Edit(Department department)
        {
            if (!ModelState.IsValid)
            {
                return View("Error", GetErrors());
            }
            
            DepartmentsRepository.UpdateDepartment(department);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Create()
        {           
            return View(new Department());
        }

        [HttpPost]
        public IActionResult Create(Department department)
        {
            if (!ModelState.IsValid)
            {
                return View("Error", GetErrors());
            }

            DepartmentsRepository.AddDepartment(department);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var department = DepartmentsRepository.GetDepartmentById(id);
            if (department == null)
            {
                ModelState.AddModelError("id", "Department not found.");

                return View("Error", GetErrors());
            }

            DepartmentsRepository.DeleteDepartment(department);

            return RedirectToAction(nameof(Index));
        }

        private List<string> GetErrors()
        {
            List<string> errorMessages = new List<string>();
            foreach (var value in ModelState.Values)
            {
                foreach (var error in value.Errors)
                {
                    errorMessages.Add(error.ErrorMessage);
                }
            }

            return errorMessages;
        }
        
    }
}

DepartsCRUD/WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DepartsCRUD/WebApp/ViewComponents/DepartmentListViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.ViewComponents
{
    [ViewComponent]
    public class DepartmentListViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string? filter)
        {
            var departments = WebApp.Models.DepartmentsRepository.GetDepartments(filter);
            return View(departments);
        }
    }
}

DepartsCRUD/WebApp/Views/Departments/Create.cshtml
@model Department

@{
    ViewBag.Title = "Create new department";
    ViewBag.Action = "create";
}

@section title_section {
    <h3>Add Department</h3>
}

@await Html.PartialAsync("_DepartmentDetail",Model)

DepartsCRUD/WebApp/Views/Departments/Details.cshtml
@model Department

@{
    ViewBag.Title = "Department Details";
    ViewBag.Action = "edit";
}

@section title_section {
    <h3>Department</h3>
}

@await Html.PartialAsync("_DepartmentDetail",Model)

<form method='post' action='/departments/delete/@Model.Id'>
    <button type='submit' class="btn btn-danger">Delete</button>
</form>

DepartsCRUD/WebApp/Views/Departments/Index.cshtml
@{
    ViewBag.Title = "Departments";
}

@section title_section {
    <h3>Departments</h3>
}

@await Html.PartialAsync("_SearchBar")


    <table class="table table-striped">
        <thread>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th></th>
            </tr>
        </thread>
        @* <tbody id="department-list"> *@
    <tbody id="department-list">
        @await Component.InvokeAsync("DepartmentList", new { filter = "" })
        </tbody>
    </table>


<br />
<a class="btn btn-primary" href='/departments/create'>Add</a>


<script>
    document.querySelector("#search-button").addEventListener("click",async ()=>{
        var filter = document.querySelector("#search-filter").value
        
        var response = await fetch(`/department-list/${filter}`);
        var departmentsHtml = await response.text();
        document.querySelector("#department-list").innerHTML = departmentsHtml;
    })
</script>

DepartsCRUD/WebApp/Views/Departments/_DepartmentDetail.cshtml
@model Department


<form method='post' action='/departments/@ViewBag.Action'>
    @if (ViewBag.Action == "edit")
    {
        <input type='hidden' name='Id' value='@Model.Id' />
    }

    <div class="row mb-3">
        <div class="col-2">
            <label class="col-form-label">Name</label>
        </div>
        <div class="col-6">
            <input type='text' name='Name' value='@Model.Name' class="form-control" />
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-2">
            <label class="col-form-label">Description</label>
        </div>
        <div class="col-6">
            <input type='text' name='Description' value='@Model.Description' class="form-control" />
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-2">
            <button type='submit' class="btn btn-primary">Save</button>
            &nbsp;&nbsp;
            <a href="/departments" class="btn btn-primary">Cancel</a>
        </div>
        <div class="col-4">
        </div>
    </div>
</form>

DepartsCRUD/WebApp/Views/Departments/_DepartmentList.cshtml
@model List<Department>

@if (Model is not null && Model.Count > 0)
{
        
            @foreach (var department in Model)
            {
                @await Html.PartialAsync("_DepartmentListItem",department)
            }
}

DepartsCRUD/WebApp/Views/Departments/_DepartmentListItem.cshtml
@model Department

@if (Model is not null)
{
        <tr>
            <td>@Model.Name</td>
            <td>@Model.Description</td>
            <td><a class="btn btn-link" href="/departments/details/@Model.Id">Edit</a></td>
        </tr>
}

DepartsCRUD/WebApp/Views/Shared/Components/DepartmentList/Default.cshtml
@model List<Department>

@if (Model is not null && Model.Count > 0)
{

    @foreach (var department in Model)
    {
        @await Html.PartialAsync("_DepartmentListItem", department)
    }
}

DepartsCRUD/WebApp/Views/Shared/_Layout.cshtml
<html>
    <head>
        <title>@ViewBag.Title</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">    
    </head>
    <body>
    @await Html.PartialAsync("_Navbar")
        <br/>
        <div class="container">
        
            @RenderSection("title_section", false)
            <br/>

            @RenderBody()

        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

DepartsCRUD/WebApp/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Departments</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/departments">Departments</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

DepartsCRUD/WebApp/Views/Shared/_SearchBar.cshtml
<div class="row">
    <div class="col-6">
    <div class="input-group mt-1 mb-1">
        <input id="search-filter" type="text" class="form-control" placeholder="Search"/>
        <div class="input-group-append">
            <button id="search-button" class="btn btn-primary" type="button">Search</button>
        </div>
    </div>
    </div>
</div>